shopngo:
  countries:
    - USA
    - UK
    - Hungary

  countryToCurrencyMap:
    USA: USD
    UK: GBP
    Hungary: HUF

  rates:
    USD: 1.0
    GBP: 0.78
    HUF: 312.79

  auctionTypes:
    - Standard
    - Lightning
    - Unlimited
    - FirstWins